"""Pydantic schemas for plans.

PlanSpec defines the structured output of the Planner.
Matches instruction.md section 9 (Plan Model).
"""

from pydantic import BaseModel, Field

from app.models.agent import AgentSpec


class WorkflowSpec(BaseModel):
    """Workflow definition within a plan."""

    type: str = Field("dag", description="Workflow type: dag, sequential, parallel")
    nodes: list[dict] = Field(default_factory=list, description="Workflow nodes")
    edges: list[dict] = Field(default_factory=list, description="Workflow edges (dependencies)")


class MemorySpec(BaseModel):
    """Memory configuration for a plan."""

    scope: str = Field("task", description="Memory scope: task, session, persistent")
    working_memory: bool = Field(True, description="Enable working memory")
    long_term_memory: bool = Field(False, description="Enable long-term memory")


class EvaluationSpec(BaseModel):
    """Evaluation criteria for a plan."""

    criteria: list[str] = Field(default_factory=list, description="Evaluation criteria names")
    threshold: float = Field(0.7, ge=0.0, le=1.0, description="Minimum passing score")


class PlanSpec(BaseModel):
    """Structured plan generated by the Planner.

    This is the primary output of the planning engine.
    It defines what agents to create, what tools they need,
    and how they should be orchestrated.
    """

    task_id: str = Field(..., description="Associated task ID")
    objective: str = Field(..., description="What the plan aims to achieve")
    summary: str = Field("", description="Brief plan summary")

    agents: list[AgentSpec] = Field(..., description="Agents to create for this plan")

    workflow: WorkflowSpec = Field(default_factory=WorkflowSpec, description="Workflow definition")
    memory: MemorySpec = Field(default_factory=MemorySpec, description="Memory configuration")
    evaluation: EvaluationSpec = Field(default_factory=EvaluationSpec, description="Evaluation criteria")

    permissions: dict = Field(default_factory=dict, description="Permission requirements")

    estimated_cost: float = Field(0.0, ge=0.0, description="Estimated cost in USD")
    estimated_duration_seconds: int = Field(60, ge=1, description="Estimated execution time")

    requires_approval: bool = Field(True, description="Whether user approval is required before execution")

    # Skills that were matched/reused (if any)
    matched_skills: list[str] = Field(default_factory=list, description="Skill IDs that were reused")